### ISSUE TITLE
POC : <esc> key handling for fiori fundamental modal ngx component 

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#1023]
**Goal**

 - Verify if the following [modal features](https://sap.github.io/fundamental-ngx/modal) are available in our currently used version
   - backdropClickCloseable
   - escKeyCloseable
   - focusTrapped
 - In case upgrade of fiori components is needed, estimate the impact of the migration in the  console  

**Reasons**

Investigation before https://github.com/kyma-project/kyma/issues/4249 is started.
We need to check how much is there provided by fundamentals out-of-the-box.

**Comment by parostatkiem** [comment]
Currently used `0.2.0` version of Fundamental-Ngx's modal doesn't support any of the mentioned properties. It turned out that they are available since version `0.3.0`. However, upgrading to `0.3.0` produces the same amount of errors as the latest version `0.6.0`.
<details>
  <summary>Errors while launching Core with F-ngx 0.6.0</summary>
 <code>
kyma-console: [1] ERROR in src/app/content/namespaces/namespace-create/namespace-create.component.ts(4,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/content/namespaces/namespace-create/namespace-create.component.ts(138,55): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/content/namespaces/namespace-create/namespace-create.component.ts(174,25): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/content/settings/applications/application-details/bindings-details-modal/bindings-details-modal.component.ts(4,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/content/settings/applications/application-details/bindings-details-modal/bindings-details-modal.component.ts(63,57): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/content/settings/applications/application-details/bindings-details-modal/bindings-details-modal.component.ts(102,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.ts(7,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.ts(82,55): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/content/settings/applications/application-details/create-bindings-modal/create-binding-modal.component.ts(158,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.ts(6,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.ts(75,53): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/content/settings/applications/application-details/edit-bindings-modal/edit-binding-modal.component.ts(140,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/content/settings/applications/create-application-modal/create-application-modal.component.ts(4,10): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/content/settings/applications/create-application-modal/create-application-modal.component.ts(30,57): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/content/settings/applications/create-application-modal/create-application-modal.component.ts(36,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.ts(37,13): error TS2345: Argument of type 'NgForm' is not assignable to parameter of type 'Type<any> | TemplateRef<any>'.
kyma-console: [1]   Type 'NgForm' is not assignable to type 'TemplateRef<any>'.
kyma-console: [1]     Property 'elementRef' is missing in type 'NgForm'.
kyma-console: [1] src/app/content/settings/applications/edit-application-modal/edit-application-modal.component.ts(44,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts(4,10): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts(29,55): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/content/settings/idp-presets/create-preset-modal/create-preset-modal.component.ts(40,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/confirmation-modal/confirmation-modal.component.ts(2,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/shared/components/confirmation-modal/confirmation-modal.component.ts(36,8): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/shared/components/confirmation-modal/confirmation-modal.component.ts(50,25): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/copy2clipboard-modal/copy2clipboard-modal.component.ts(3,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/shared/components/copy2clipboard-modal/copy2clipboard-modal.component.ts(28,55): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/shared/components/copy2clipboard-modal/copy2clipboard-modal.component.ts(36,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/information-modal/information-modal.component.ts(3,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/shared/components/information-modal/information-modal.component.ts(36,51): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/shared/components/information-modal/information-modal.component.ts(43,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/json-editor-modal/json-editor-modal.component.ts(2,24): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/shared/components/json-editor-modal/json-editor-modal.component.ts(33,50): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/shared/components/json-editor-modal/json-editor-modal.component.ts(42,23): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/json-editor-modal/json-editor-modal.component.ts(54,27): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts(5,10): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts(26,51): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts(58,27): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/resource-uploader/resource-uploader-modal/resource-uploader-modal.component.ts(78,27): error TS2339: Property 'close' does not exist on type 'ModalService'.
kyma-console: [1] src/app/shared/components/role-binding-modal/role-binding-modal.component.ts(7,10): error TS2305: Module '"/Users/i354699/Sites/kyma-project/console/core/node_modules/fundamental-ngx/fundamental-ngx"' has no exported member 'ModalComponent'.
kyma-console: [1] src/app/shared/components/role-binding-modal/role-binding-modal.component.ts(108,53): error TS2339: Property 'result' does not exist on type 'ModalRef'.
kyma-console: [1] src/app/shared/components/role-binding-modal/role-binding-modal.component.ts(116,23): error TS2339: Property 'close' does not exist on type 'ModalService'.

</code>
</details>

#### In a summary, we **have to** upgrade Fundamental-ngx to the latest version to be able to use mentioned features.

**Comment by parostatkiem** [comment]
During the long research, I was able to successfully introduce Fundamental-NGX `0.6.0` to Console and I saved my work on a branch that can be used in the future.

What's more, I developed a way to focus first input modals. I submitted an issue for it: https://github.com/kyma-project/console/issues/1034
