### ISSUE TITLE
Prevent remote libs and services spoofing

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#105]
**Description**

System uses external 3rd part libraries and resources: 
- External 
 -- Google webfonts
- Internal
 -- APIs
 -- Cluster 
 -- ...

**Risk**

In case any of those external system were compromised, we could leak sensitive information.

In case any of those systems were using plain http instead of TLS, we would be leaking information on several devices plus we would allow mitm attacks. 

In case of external libraries, existing vulnerabilities could be leveraged to compromise our system or our customers.  

**Suggested Mitigation**

 * Use only TLS to connect to services in order to prevent the service for being spoofed and to provide end to end encryption. 
 * In case of external libraries, as such providing JS code, evaluate the possibility of coming up with a secure version and stick with that one. Such the case, evaluate the possibility if implementing SRI ([https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)]
 * Confirm there is a vulnerability management in place covering external libraries being used.

**Comment by kwiatekus** [comment]
One remaining thing to do in this task is to get rid of http reference to google webfont.
It will be done once we use luigi framework in the console

**Comment by jesusreal** [comment]
The font 'Open Sans' is still used by Techné dependency. Once we migrate to Fiori Fundamentals there should not be any external fonts loaded. We will check again once this ticket is done: https://github.com/kyma-project/console/issues/522

![Screen Shot 2019-02-13 at 12.29.39.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/218df457-df76-487e-b82c-2fe1a92cf98f)
![Screen Shot 2019-02-13 at 12.29.21.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/3cb02306-44b2-4b6d-953d-141a85097cf0)

**Comment by jesusreal** [comment]
After console#116 it is not possible to load external fonts, so actually we don't need to wait for console#522 to be finished.

![Screenshot 2019-03-04 at 15.32.37.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/58a0c543-10d8-4d11-ae4d-4a135b7afd53)

No changes were required, therefore no pull request will be filled

Note: in order to reproduce the case shown in the attached screenshot, you need to do the following change on master branch, since external font loading for techné is actually broken there:

![Screenshot 2019-03-04 at 15.34.34.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/4a627ae6-c33f-4b68-b804-965926480ec3)

**Comment by jesusreal** [comment]
Fixed by #116
