### ISSUE TITLE
Order of the functions in the functions list

### ISSUE THREAD

**Issue by VishnAndr** [kyma-project/console#1968]
**Description**

The sort order in the list of functions should remain the same.

Previously the list of functions has been sorted by functions names (at least in 1.11.1 the latest I've seen it was working this way). Now it looks like a completely random order in 1.15 which shuffles with each access.

**Reasons**

Each time the user accesses the list of functions, it is sorted in some 'random' order, completely different from the previous access.
When having multiple functions (~20) it's quite annoying. The search option is great but it's an additional step.

**Attachments**

How to reproduce:
1. navigate to functions list
2. notice a sequence in which functions are listed
3. open any function
4. go back to functions list again pressing either the entry in the left-hand side menu or top left corner link Functions (above the function name)
5. notice that the sequence is completely different

Kyma version 1.15

**Comment by kwiatekus** [comment]
We plan to replace console component with [busola](https://github.com/kyma-project/busola). You can install busola locally and have it serve you as a UI for kyma runtime.

In busola project the bug is already fixed. All lists are realised via generic list component with sorting.
This bug will not be fixed in console.
