### ISSUE TITLE
Console-web test never ends despite it's green

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#2012]
**Description**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1310911389220474880

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by Wawrzyn321** [comment]
It turns out the `console-web` hadn't actually passed - from the attached logs, we can see that the functions test has passed (one before last), and the last one, docs tests, isn't included in log. What's more, `console-web` is still in `Running` phase, with other tests `NotYetScheduled`, so the issue is more about `console-web` timeouting the pipeline.

**Comment by pbochynski** [comment]
We are going to replace that test with other. No fix will be provided.
