### ISSUE TITLE
Handle empty references to Service Class on Service Instance view

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/console#271]
As @derberg suggested, we need to:

- Revisit the Create binding tooltip content, when Instance doesn't have references to Service Class
- Figure out how to tell the user, what he should do to (if he can restore the empty references, etc.)?

09/09/2019 ---

Currently it is impossible to view service class instance detainls in case service class was removed.
See the following attachment:
![Screen Shot 2019-09-09 at 13.44.05.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/5bd0b645-bce2-481a-a8e5-a2445d8430da)

**Comment by derberg** [comment]
@pkosiec we need this issue to contain more details and reflect current situation. For example the Create binding button doesn't exist any more, what is is about then?

**Comment by jose-cortina** [comment]
Although this issue is considered critical, it can only be reproduced on very specific circumstances, and the fix is effort-intensive.
It does not block the 1.8 release and is planned for 1.9.

**Comment by kwiatekus** [comment]
In case application brokers and helm brokers disappear, the classes also disappear.
This shouldn't be the case if users have instances of the classes in their namespaces:
https://github.com/kyma-project/kyma/issues/6319
https://github.com/kyma-project/helm-broker/issues/54

Due to those issues, the service instances have empty references to service classes. Therefore, we dont know where to display such instances (Addon or Service classification is part of the service class object).

Until the bugs are fixed, lets display those instances in Addon tabs (as a fallback - as this is the tab opened by default)
