### ISSUE TITLE
Remove internal confirmation modal

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/console#367]
**Description**
Remove the internal confirmation of leaving a page with dirty state. Instead of that, just send a message to LuigiClient and then Luigi will take care of it.

**Reasons**
𝔩𝔲𝔦𝔤𝔦𝔣𝔦𝔠𝔞𝔱𝔦𝔬𝔫

**Attachments**
### The Pull Request:
https://github.com/jesusreal/console/pull/11

**Comment by maxmarkus** [comment]
Issue one: If you enter only Function name and click on Cancel, no dirty state is triggered
Issue two: It should also trigger dirty state when leaving the current view (when opening a modal), I created an issue at lambda, but maybe happens because our change here. Please check. https://github.com/kyma-project/console/issues/368
