### ISSUE TITLE
Service Catalog UI doesn't display errors on create and delete actions when SC apiserver is down

### ISSUE THREAD

**Issue by PK85** [kyma-project/console#448]
**Expected result**
Nice error message in UI.

**Actual result**
Nothing happen in UI on delete actions (SI and SB), on create spinning icon.

```
{data: {createServiceInstance: null},…}
data: {createServiceInstance: null}
createServiceInstance: null
errors: [{message: "internal error [environment: "production", name: "uuid-service-lean-fly"]",…}]
0: {message: "internal error [environment: "production", name: "uuid-service-lean-fly"]",…}
message: "internal error [environment: "production", name: "uuid-service-lean-fly"]"
path: ["createServiceInstance"]
```

**Steps to reproduce**
Kill SC apiserver by updating deployment to not existing image.

**Comment by derberg** [comment]
question is if we really want to see an error message:
- if I'm in SC context in the UI when the server fails, yes, I want to see a good error message
- if I'm not in SC context in the UI or not even in the Console and access the console when SC apiserver is down, I'd like UI to be resilient and not show the SC related UIs at all, then in other contexts where SC functionality is needed some nice error. Nice approach would be that SC views are in navigation, but grayed out with error in tooltip

**Comment by derberg** [comment]
@PK85 let us clarify few things
- the view/read part of the Catalog UI works fine because we take data from backed cache and are resilient to apiserver unavailability. Do you consider it as bad or good? would you expect Catalog UI fails because the cache is empty due to the properly executed invalidation?
- What you mean by a nice error in the UI? I think that nice error message would be "Service Catalog is unavailable. Contact your administrator" and in the backend we would put much more logs for the administrator to figure out the cause. Question is how we can nicely figure out that the reason is that the apiserver is down so we can put it in the logs

**Comment by PK85** [comment]
Answer to 1) You are right, GET operation is ok, but CREATE and DELETE should fail right?
Answer to 2) yes the notification coulkd display that ServiceCatalog CRD doesn't exists.

**Comment by kwiatekus** [comment]
No longer an issue since SC was refactored to use CRDs.
