### ISSUE TITLE
Make Kubeless a Module

### ISSUE THREAD

**Issue by joek** [kyma-project/console#501]
**Description& Reason**
As a preparation for knative (and to make the core less fat), we should move kubeless out of the core and make it a dedicated module. This will enable us to not install kubless in the future and reduce the work inside core for updates.

AC:
- Kubless and Lambda UI is a module by its own
- Kubless is installed by default
- Validate if Grafana Dashboards are still working
- Adjust tests

**Comment by sayanh** [comment]
There are few blockers I found with the upgrade process while working on this issue:
- The deletion of CRD is not possible as this will remove all the resources created in the old version of Kyma. Hence this will break the upgrade test.
- Can we skip installation of the CRD in the upgrade process? May be. So I tried to add helm `pre-upgrade` for a chart which will get installed before `kubeless`. I chose `cluster-essentials`. Now the installer does not only does `helm install` but also `helm upgrade`. Turns out [this](https://github.com/kyma-project/kyma/pull/3583/files#diff-a71c1b92dfb18d8fe30df0062a4e653a) approach fails to install a fresh version of Kyma. As the installation process triggers the upgrade of `cluster-essentials` which in turns triggers the pre-upgrade hook during installation. Meaning the CRD fails to get installed in the fresh installation.

There can be a way to upgrade by substituting values in [here](https://github.com/kyma-project/test-infra/blob/master/prow/scripts/cluster-integration/kyma-gke-upgrade.sh#L431) but this is not how upgrade should be done as per https://kyma-project.io/docs/root/kyma/#installation-update-kyma

It is really unclear, how upgrade should be done when breaking changes in helm charts.

**Comment by sayanh** [comment]
As discussed with @joek, right now as this is impossible to modularize kubeless based on the current behavior of the installer, we would skip it. The ultimate goal is to use knative for FaaS which will then solve this issue once and for all.
