### ISSUE TITLE
Role binding / create namespaces binding modals - dropdown width too small

### ISSUE THREAD

**Issue by y-kkamil** [kyma-project/console#661]
**Description**

Dropdowns in role binding & create namespaces binding modals have width that is too small.
![Screen Shot 2019-03-11 at 10 50 49](https://user-images.githubusercontent.com/13983249/54114831-8dfc2b80-43eb-11e9-97b2-05695b975f1d.png)

![Screen Shot 2019-03-11 at 10 49 42](https://user-images.githubusercontent.com/13983249/54114784-70c75d00-43eb-11e9-9abf-b17a35b75b57.png)

**Comment by hardl** [comment]
Please clarify if fixed and merged to master and then close

**Comment by marynaKhromova** [comment]
This issue has been fixed within this task https://github.com/kyma-project/console/pull/680

**Comment by jesusreal** [comment]
Already fixed in current master branch

![Screenshot 2019-03-20 at 14.52.47.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/e84e6b39-9d81-427b-9267-54998830a952)

![Screenshot 2019-03-20 at 14.51.53.png](https://images.zenhubusercontent.com/5b90f41c0e23a90b8f9c4f5d/3442a172-fecb-4696-a078-fd51352349c4)
