### ISSUE TITLE
List of applications is not loaded after editing one entry

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/console#662]
**Description**

The list view of applications is not loaded after editing one entry. No error is shown, just an empty page, DOM is empty.
![Screen Shot 2019-03-11 at 10.47.25.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/9c97cf2d-c6a4-40df-abe3-497c1f1e39a8)

Appears in Chrome v 72.0.3626.119 

**Steps to reproduce**

* go to applications 
* go to the details view of one ot the applications
* click the 'edit' button and add a label to the application
* go to the list view (using the link at the top left)
![Screen Shot 2019-03-11 at 10.58.36.png](https://images.zenhubusercontent.com/5b8399bea1576a587faa4a80/5947c05f-5662-451e-9b32-8f11701e0d9f) 
* the list view is not rendered. Even after clicking the `applications` link on the left side navigation doesn't fix that even though it should re-render the whole frame.

**Comment by jesusreal** [comment]
Bug fixed by removing _href="#"_. Global missusage of links is out of scope of this ticket. Follow up ticket for that:

Additionally, breadcrumb links on Firefox were hardly clickable due to Fiori Fundamentals having following style applied:
```
.fd-breadcrumb {
 margin-bottom: -12px;
}
```
Discussed with another colleague and as both consider this a potential source of bugs, created a ticket for Fiori Fundamentals:
