### ISSUE TITLE
E2E UI test for exposing API

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#749]
**Description**

Implement a UI test with the following scenario:

- create a new resource using yaml uploader (simple hello world service : deployment + service) : [yaml](https://app.zenhub.com/files/139590577/3f7dd0b0-b478-4ac6-a74b-52e8f23040b9/download)
- expose API
- check if api endpoint is available
- secure api with dex IDP
- check if endpoint returns 401 Unathorized w/o token header

**Reasons**

To increase e2e tests coverage

**Comment by parostatkiem** [comment]
#### Sadly, the first bullet point is impossible to be done due to a technical reason.

The only way of uploading file in Puppeteer is `ElementHandle.uploadFile` which is enough in most cases. However, in Console we don't use conventional upload form. We disable the _Upload_ button until the file is uploaded and it works in real life, when the file is uploaded using `fileUploadDialog` or Drag&Drop. Puppeteer's way of just putting a file into the file input doesn't trigger the mentioned event. It seems to be a known problem with lots of people waiting for it to be resolved.

#### I see 3 solutions for this problem:
- wait until Puppeteer resolves [**this issue**](https://github.com/GoogleChrome/puppeteer/issues/1376)
- change the mechanism in Console (no idea for now how it could be done with keeping current behaviour)
- deploy the yaml "behind the scenes", eg. using Kubernetes

If you want to see it in action, switch to [this branch](https://github.com/parostatkiem/console/tree/e2e-expose-API) and execute `npm test` in `/tests`. Notice that _Upload_ button is still disabled.

**Comment by kwiatekus** [comment]
I'd say lets go for option 3 : apply the yaml _behind the scenes_
We should also allow uploading resources by pasting the content into yaml editor (not part of this task)

**Comment by jesusreal** [comment]
I came up with an easier solution I will create a Lamda, since this creates a Deployment and a Service. I will remove the Lambda in the tear down part of the test.
