### ISSUE TITLE
Console cleanup and install takes a long time

### ISSUE THREAD

**Issue by miltonc** [kyma-project/console#98]
**Description**
npm run clean
It took about 15 min to clean up

Similarly for the install as well

**Comment by magicmatatjahu** [comment]
Hi Milton!
Thanks for your interest about the Kyma project.

Regarding to your problem: The amount of time it takes to install or remove dependencies is proportional to the speed of your internet connection and/or the speed of your computer.
We sometimes also have a problem with installing packages, because the connection in our office sometimes likes to be slow :) If you do not want to wait and would like to try the console, you can always go to `http: //console.kyma.local` (of course, if you have installed Kyma) or if you want to test only one view, go to appropriate folder and follow the instructions.

On behalf of the entire Kyma team, I greet and look forward to your first contribution!
