### ISSUE TITLE
Protect consoleUI against XSS/Clickjacking from microfrontends

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/console#99]
**Description**

Placement information of microfrontends is included in the microfrontend definition (etcd). Such information is used by the consoleUI to render microfrontends. 

**Risk**

Microfrontends placement could be leveraged to perform XSS or Clickjacking attacks in the consoleUI top level window. 
Risk accepted on 03/Jul/18 by @gopikannappan  

**Suggested Mitigation**

- ~Restrict scheme of iframe URL to https~  (done)
- Handle mircrofrontend elements (e.g. labels, buttons, descriptions) that are incorporated into Console UI document in a secure manner. Either perform HTML output encoding or strict sanitization, with a whitelist policy for the type of data to be included. In any case, following content should be avoided:
      - Avoid CSS
      - Avoid JS
      - Avoid plugins (embed, objects tags, ...)
      - Avoid applets
- Document suggestions for Microfrontend implementation security, e.g.:
should specify content-type, include also X-Content-Type: nosniff
should use HSTS

**Comment by kwiatekus** [comment]
We should check if anything that is defined in the MF or CMF CRD could end up in the DOM tree of the microfrontend. If so, it should be properly validated

**Comment by jesusreal** [comment]
Findings:
- Console is already taking care of sanitizing any input from microfrontends, since it is using Angular´s built-in sanitization mechanism. Can be tested by adding [this microfrontend](https://app.zenhub.com/files/139590577/2fa5498c-8c63-4537-b886-c34e5224a52d/download) through console UI

Done:
- Add following line to every nginx config file in console repo: `add_header X-Content-Type-Options: 'nosniff';` 
- Add docu with security recommendations for microfrontend resources: https://github.com/kyma-project/kyma/pull/2783
